### ISSUE TITLE
[ESS API support] Default ecctl URL configuration to ESS API

### ISSUE THREAD

**Issue by Kushmaro** [elastic/ecctl#159]
## ecctl should default to ESS
When initializing ecctl, we should ask the user for an API url, but default to the ess Public API

### Init command text
From: “Enter the API URL of your ECE installation”
To: “Enter the custom API URL for your Elastic Cloud Enterprise or Elastic Cloud environment, or hit enter to use Elasticsearch Service by default”

### Following configurations
- If the user opts to use ESS, we should suggest API authentication only as suggested in #157 
- If the user opts to use ESS, we should ask for the default region to work against #162

**Comment by zanbel** [comment]
Wanted to add that I'm on the fence about not requiring users to explicitly choosing between ECE and ESS since I think it will reduce confusion and will treat both in the same way. E.g. we can add the following step:
```
Select if this configuration will be used with:
  [1] Elastic Cloud Enterprise
  [2] Elasticsearch Service // (or [2] Elastic Cloud)
```

Another thing to keep in mind is whether the term used should be `Elastic Cloud` or `Elasticsearch Service`. Currently ecctl only allows users to interact with the Elasticsearch Service, but even if we decide to go with the more future proof option, which is fine, please make sure we don't use `Elastic Cloud service`.

**Comment by Kushmaro** [comment]
@zanbel as mentioned in the email thread, I'd still want to default to ESS in the URL section, without an explicit choice, as most users will be ESS users.

“Enter the custom API URL for your Elastic Cloud Enterprise or Elastic Cloud environment, or hit enter to use Elasticsearch Service by default”:

**Comment by karencfv** [comment]
Thank you both for the input for the workflow 🙂  I have the following to add:

I agree with @Kushmaro that the default should be the ESS api host address and I also agree with @zanbel about the format of the step to avoid confusion. Having the step formatted in that way, apart from being consistent with the rest of the workflow, allows us more flexibility in the future to add ESSP, GovCloud etc.

I have already made a PR with the changes, to get this issue moving along and we can make adjustments as required.
