### ISSUE TITLE
[Discuss] Automatic asciidoc generation and live docs

### ISSUE THREAD

**Issue by karencfv** [elastic/ecctl#256]
## Description
After https://github.com/elastic/ecctl/pull/249 was merged, we now update asciidocs on every PR.

This works great to keep the docs build green, but it also means that we'll be updating the live documentation as well. The latest changes have only been to remove commands, so it's not a big deal. 

This does mean, however, that our live documentation will not accurately reflect what is on the latest release. For example, new commands or features.

There are a few options we can have here that I can think of but please feel free to add any I haven't thought of.

- We keep it as is and make a disclaimer in the docs that this is from the master branch and not the latest release.

- We stop updating the docs on every PR, with the exception of removed commands, and only update them during a release.

- We point the live docs to the latest release tag. Although this would mean making amends would be a little trickier.

cc @nrichers

**Comment by gtback** [comment]
In my opinion, it's preferable to keep doc updates and code updates in the same PR, so they can be reviewed together and make it easier to find the code change that occurred at the same time the docs changed (and vice versa)

It's possible to build multiple branches, designate one (probably the latest release) as the default, and put a banner on another version (like `master`) with the caveat that the features described on that page may differ from the released version. Using a branch rather than a tag makes it possible to update the documentation for typos, etc. without needing to tag a new release of the code.

**Comment by gtback** [comment]
Also, I've been thinking that we should remove the Edit links from the automatically-generated AsciiDoc; any changes to these files will get overwritten the next time the docs are auto-generated. At a minimum, we could add a banner explaining that they are built from the Go source. Even better, we could try to link directly into the Go code.

**Comment by nrichers** [comment]
Chatted with @karencfv a bit and she'll set something up to chat further, with a big thank you to her. The TL;DR: for my comments below is that we might want to consider cutting branches for the docs builds when we release new versions of ecctl, unless the ecctl devs are interested in changing how they handle releases. 

Some additional notes on @karencfv's comments:

> We keep it as is and make a disclaimer in the docs that this is from the master branch and not the latest release.

There is a precedent for this in the Elastic Stack docs for docs built from `master`, but we usually provide some release docs that people can refer to as well. We probably don't want to have _only_ the `master` docs, as it makes it hard to know what's available in any given release. As in, we need more than just this suggestion, I think. 
 
> We stop updating the docs on every PR, with the exception of removed commands, and only update them during a release.

I kinda gasped when I read this suggestion. 😁 Typically, docs go with the code and we shouldn't be breaking that model, as this option would go against what the rest of Elastic does. (This is the scary option!)

> We point the live docs to the latest release tag. Although this would mean making amends would be a little trickier.

I have cut branches in the past just for the docs (e.g. ECE beta branches), so that might be an option. Less than ideal, but workable and in line with what @gtback suggests in terms of "[u]sing a branch rather than a tag." 

(Our doc builds work based on branches and AFAIK there's no support for release tags today. If ecctl doesn't do release branches, you can really only ever build the latest content from `master`. Unless @gtback has a magic trick up his sleeve.)

And this comment from @gtback:

> Also, I've been thinking that we should remove the Edit links from the automatically-generated AsciiDoc; any changes to these files will get overwritten the next time the docs are auto-generated. 

Good point. This is an issue not just for the ecctl docs but also for other generated docs we have today (such as the Open API reference docs for ECE and ESS). We should probably chat more about how we can prevent people from editing docs that aren't actually editable without regenerating the Asciidoc source.

**Comment by gtback** [comment]
I certainly don't want to tell the ecctl team how to do versioning or use git 😂 , but having a branch for each minor (X.Y) release, which could be used for bugfixes on that branch and always has the most up-to-date version of the docs for that minor release, would match the existing docs build process. It wouldn't be too hard to also build tags, but by the nature of git you could never add/update/fix the docs for a certain tag. Other doc build systems (readthedocs.org is the one I'm most familiar with) support both tags and branches.

**Comment by karencfv** [comment]
Closing this as we have come to an agreement with @nrichers to use a separate branch for docs only.
