### ISSUE TITLE
provide examples of integrating ecctl with ansible and terraform for usage to ECE and ESS Cloud

### ISSUE THREAD

**Issue by 111andre111** [elastic/ecctl#261]
It's great that is provided the ecctl tool.
The more that there is the upcoming cloud ESS variant.
Now, in the documentation here:
https://github.com/elastic/ecctl/blob/master/docs/ecctl-getting-started.asciidoc
there is mentioned to use the tool with ansible or terraform.

It would be great if there will be provided some examples of how to exactly use ansible and terraform with ecctl.

**Comment by marclop** [comment]
@111andre11 The text sounds like something that we might've ended up written for elastic/cloud-sdk-go rather than ecctl, but I'll let @nrichers comment on that.

`ecl` could be used as any other binary in an Ansible Playbook to perform certain tasks, assert ecctl or change them.

The same can be said for the Terraform mention in the docs, elastic/cloud-sdk-go is the foundation upon which ecctl is built. The only possible way to use ecctl in Terraform would be as a shell executed binary, same as Ansible. I think we need to rephrase or clarify the documentation so that there's no doubts on what that means and actually, it's probably better to remove that sentence and add it in the cloud-sdk-go.

**Comment by 111andre111** [comment]
Ok thank you @marclop That makes sense
